// Package aid_module comment
// This file war generated by trpc4videopacket 1.0
// Generated from aid_module.jce
package aid_module

type EnumVidType int32

const (
	EnumVidType_E_UNKNOWN = 0
	EnumVidType_E_LONG    = 1
	EnumVidType_E_SHORT   = 2
)
