// Package aid_module comment
// This file war generated by trpc4videopacket 1.0
// Generated from aid_module.jce
package aid_module

type ErrorCode int32

const (
	ErrorCode_E_PKG_DECODE = -4001001
	ErrorCode_E_SYS_ERROR  = -4001002
)
